### ISSUE TITLE
Fit Galacticus magnitudes/luminosities to CatSim SED library

### ISSUE THREAD

**Issue by danielsf** [LSSTDESC/DC2_Repo#38] opened 2017-11-09 23:15 UTC
In order to generate PhoSim-ready InstanceCatalogs, we have to be able to tell PhoSim where to find SEDs for the sources we are simulating.  Since Galacticus only outputs magnitudes and luminosities, it has been decided that we will just do a best-fit association with the SEDs in CatSim's library and feed those SEDs into PhoSim.  Performing this association has proven to be more tricky than I thought.

The attached plot shows the apparent magnitude residual as a function of R_v = A_v/E(B-V) for the six LSST filters.  I am plotting against R_v because the way that Galacticus assigns dust parameters has proven to be one of the difficulties (I have already backchanneled @evevkovacs about this, and she says that the Galacticus team is working on it).  In each plot, the horizontal axis is R_v.  The vertical axis is the apparent magnitude of the best-fit SED with dust applied minus the same quantity as reported by Galacticus.  The colorbar corresponds to the number of sources in that pixel of the plot.  This plot is only for the disk components of galaxies.

As I said, there appears to be a problem with how Galacticus assigns dust parameters, because we get some very large values of R_v.  Even if we were to cut out those anomalously high-dust galaxies, we would still have magnitude residuals of the order a few 0.1 magnitudes, especially in the bluer bands.  Is this acceptable?

Another question: The Galacticus magnitudes in this plot are calculated as follows:

- take `f = LSST_filters/diskLuminositieStellar:LSST_*:observed:dustAtlas`
- set `m = -2.5*log10(f)`
- set `m = m - 5.0*log10(1+z)`

That last step confuses me.  I was told to expect to be off by a single `2.5*log10(1+z)`, since Galacticus does not apply the stretching of photon frequencies when calculating its 'observed' luminosities.  However, to get good agreement with the CatSim fits, I had to subtract `2*2.5*log10(1+z)`.  I am both surprised by the extra factor of 2 and by the fact that I had to subtract rather than add.  Could the Galacticus experts speak to what I should have to do to f in order to get the actual magnitude observed by LSST? @evevkovacs @dkorytov 

![rv_dmag_dist](https://user-images.githubusercontent.com/1682854/32634473-b08d4fc2-c560-11e7-8788-d497a8cb78e6.png)

**Comment by evevkovacs** [comment] 2017-11-09 23:47
We will look into this. BTW, for the record, in Galacticus, the relationship between the observer-frame luminosities and the apparent magnitude  (which measures flux) should be:
m_apparent= -2.5log_10(Luminosity in observer frame)+ mu -2.5log_10(1+z)
where mu is the distance modulus. (The reason is that Galacticus does not bother to carry the (1+z) common factor throughout the luminosity calculation)
@egawiser This catalog currently contains both luminosities and magnitudes. Will the filter luminosities be of use to the working groups, or are they solely interested in magnitudes?

**Comment by danielsf** [comment] 2017-11-09 23:54
What distance is used in the distance modulus?  My understanding is that, in cosmological contexts, the `-2.5*log10(1+z)` factor should already be included in the distance modulus, because of the `(1+z)` factor in the luminosity distance.  Are you using the angular diameter distance to calculate the distance modulus?

**Comment by evevkovacs** [comment] 2017-11-10 02:15
My understanding is that mu is the luminosity distance and the factor of (1+z) comes from the change of  integration variable  when integrating the SED over the  blue-shifted filter band pass. ie the endpoints of the integration change, and there is a scale factor change of 1+z.

**Comment by egawiser** [comment] 2017-11-10 02:45
@evevkovacs I agree with that explanation.  The solution to some of these questions would be to use flux densities in microJansky instead of magnitudes.  The familiar formula is 
L = f* 4 pi d_luminosity^2 .  But for flux density in f_nu units (which is the case for microJansky or AB magnitudes), you have to divide d_luminosity^2 by (1+z).  You would think that the distance modulus would include this, since it converts between absolute and apparent magnitude but it doesn't - this was initially defined for low-redshift applications, so that term is in the infamous "k correction" that is part of the official M-m formula but seldom written out explicitly in textbooks.

Filter luminosity densities (in L_nu units) would seem to be potentially of interest, but if they can be derived from the filter magnitudes and true redshift using a stated formula, it shouldn't be necessary to list them in the catalog.

**Comment by egawiser** [comment] 2017-11-10 02:50
@danielsf I'm really baffled why you're varying R_V, and over such a wide range while trying to find the best-fit CatSim SED template to the reported Galacticus photometry.  I don't know what dust model Galacticus is using, but I'd bet R_V is in the range of 3 to 4 and possibly a fixed value if a single dust law is being assumed for all galaxies.  Without more information on how Galacticus modelled the dust, I don't think this approach to fitting will be very meaningful.

**Comment by danielsf** [comment] 2017-11-10 04:11
I am not varying R_v.  I am taking it from Galacticus.  Galacticus also returns V and B band magnitudes with and without dust.  I am using those magnitudes to find the A_V and E(B-V) that Galacticus reports and using that to set R_V.  The anomalously large R_V values are due to a known bug in how Galacticus interpolates fluxes from its star formation model (at least, this my understanding from private communications with Eve).

**Comment by danielsf** [comment] 2017-11-10 04:11
Thanks for the explanations on the magnitude-versus-flux problems.  I will compare them to what I am finding in my fits and make sure that the minus signs all line up.

**Comment by egawiser** [comment] 2017-11-10 14:16
Thanks for explaining the R_V situation.  As long as everything you're using is in rest-frame B and V bands, that should be self-consistent - though it's still hard to understand how the apparent bug produces such crazy R_V.

**Comment by evevkovacs** [comment] 2017-11-10 17:55
@egawiser  @danielsf  It's not the star-formation model but the dust correction that is the problem. The dust correction is computed by interpolating or extrapolating a set of look-up tables which depend on galaxy properties. Sometimes that interpolation/extrapolation goes haywire. Andrew Benson worked a lot on fixing this, but it seems to have cropped up again. Rv is crazy because the dust correction produces a totally extincted galaxy.

**Comment by evevkovacs** [comment] 2017-11-12 18:01
And just to be completely explicit, here is the formula for converting Galacticus observed luminosity to apparent magnitude:
     m = -2.5*log_10(L) - 2.5*log_10(1+z) + 5*log_10(DL(z)) + 25
where L is the luminosity, DL(z) is the luminosity distance in Mpc, and the 25 comes from converting Mpc to pc (because absolute magnitude is defined at a distance of 10 pc). For observed luminosities, the SED of the galaxy is integrated over the blue-shifted wavelength range of the observer-frame filter.

**Comment by danielsf** [comment] 2017-11-13 21:36
Okay.  I now have the SED fitter working such that the magnitudes I get from the fit SEDs are consistent with the conversion between Galacticus flux and magnitude given by Eve above.  That being said, there is still a bit of slop.  These figures compare the Galacticus magnitudes to the SED magnitudes with and without dust for a random set of 56,000 galaxy disks. The numbers next to the plot titles are the first, second, and third quartiles in `|m_galacticus - m_SED|`.  I am posting these in case anyone feels that a disagreement of `0.1` magnitudes is totally unacceptable.

![rv_dmag_dist_dustless](https://user-images.githubusercontent.com/1682854/32750479-a453fa70-c877-11e7-88c4-68c224e23b4a.png)
![rv_dmag_dist](https://user-images.githubusercontent.com/1682854/32750485-a6f2907a-c877-11e7-8541-ef3812baa069.png)

**Comment by drphilmarshall** [comment] 2017-11-14 02:23
Cool, thanks Scott! This looks like it needs some science team inspection: @fjaviersanchez which DC2 analysis paper authors should be looking at these plots?

**Comment by dkorytov** [comment] 2017-11-17 20:46
Hey Scott (@danielsf), which redshift are you are using to calculate the magnitudes? The default "redshift" has the effect from peculiar velocities included. "redshift_true" is cosmological redshift and it's the value that I use to compute magnitudes in protoDC2.  Maybe this is the cause? I've did a quick test:

![screenshot from 2017-11-17 14-48-53](https://user-images.githubusercontent.com/25048061/32968202-f5fc1cdc-cba5-11e7-955d-37a34dd66e66.png)

**Comment by danielsf** [comment] 2017-11-17 21:08
@dkorytov Right... I am using the total redshift.  I will change that.  I probably won't have time to re-run my validation test today.  I'll try to rerun the validation test and post new results in the next few days.

Nice catch.

**Comment by evevkovacs** [comment] 2017-11-17 23:10
Pardon my ignorance, but which is the best one to use? The luminosity distance is usually calculated in terms of the cosmological redshift, and as you go out in z, the peculiar velocity matters less.  But I would think that the (1+z) factor for the photon frequencies would be affected by the peculiar velocity, as would the limits of integration over the filter.  The last point is moot, because we are not even k-correcting the filter luminosities for the change from snapshot redshift to lightcone redshift.  What exactly do the observers measure? I have asked Eric Gawaiser the above question, but he hasn't answered yet.

**Comment by egawiser** [comment] 2017-11-20 18:36
I agree with @evevkovacs that luminosity distance only depends on the cosmological redshift but that a doppler shift caused by peculiar velocity further affects the frequency of each photon and hence flux density (=magnitude).  Peculiar velocity should cause scatter but not bias, as seen in Dan's plot.   Scott could test this by plotting magnitude discrepancy versus redshift (and even more directly, magnitude discrepancy versus peculiar velocity).  But sure, if the discrepancy disappears after switching to redshift_true, no need to worry about this further.

**Comment by danielsf** [comment] 2017-11-20 20:28
Distinguishing between true redshift and full redshift does not improve the scatter plots above.  If people want to check my work, the data for the plots is generated by this script

https://github.com/danielsf/gcr-catalogs/blob/check_redshift/GCRCatSimInterface/validation/test_sed_fitting.py

@evevkovacs Regarding the `2.5*log10(1+z)` factor that must be added to the catalog magnitudes to get the actual magnitudes: is that `z` true or full?

**Comment by danielsf** [comment] 2017-11-20 23:30
Correcting that error on my part did not seem to help the scatter

**Comment by evevkovacs** [comment] 2017-11-20 23:44
I took a quick look at your code but haven't digested it yet. Can you see if there is any z dependence to the scatter? That might give us a clue.

**Comment by evevkovacs** [comment] 2017-11-27 15:33
@danielsf @dkorytov  OK, sorry I have been asleep at the switch. The Galacticus luminosities for both the LSST and the SED filters are all evaluated at the snapshot redshifts. If you are doing a consistency check between your fits to the SED filters and the Galacticus values for the LSST filters, you need to use the snapshot redshifts for each galaxy, rather than the lightcone redshifts. I believe that Dan has saved the snapshot  number for each galaxy in the galaxy properties. We will need to give you a table that converts that to redshifts. I have it somewhere and will find it and will send it to you. In the next catalog iteration we will add that table to the catalog metadata.

**Comment by yymao** [comment] 2017-11-27 15:41
@evevkovacs what's the difference between `redshift_true` and snapshot redshift?

**Comment by evevkovacs** [comment] 2017-11-27 15:46
redshift_true is the lightcone redshift (ie redshift obtained when galaxies, which have been evaluated  at the simulation snapshots are interpolated onto the observer's lightcone). (Recall that the SAM is run on the simulation snapshots)

**Comment by danielsf** [comment] 2017-11-27 23:34
@evevkovacs's insight that the observer frame luminosities are at snapshot redshifts improves the fit, but only marginally.  I also plotted the magnitude fits in the rest frame (which should be immune to the effects of diverse redshift definitions).  There is still a delta_magnitude between Galacticus' calculations and the CatSim SEDs on the order of a few 0.01 magnitudes.  Recall that the numbers in the title of each plot denote the first, second, and third quartiles in delta_magnitude.

(the plots are all combinations of rest/observer frame and dust/no dust)

![rest_frame](https://user-images.githubusercontent.com/1682854/33295064-5dea2e44-d388-11e7-8f2d-30a4ce1c4e6e.png)
![observer_frame](https://user-images.githubusercontent.com/1682854/33295071-6104a208-d388-11e7-8fac-2b6e32474b61.png)
![rest_frame_no_dust](https://user-images.githubusercontent.com/1682854/33295073-64030968-d388-11e7-978a-6c5d050d6694.png)
![observer_frame_no_dust](https://user-images.githubusercontent.com/1682854/33295076-6656d154-d388-11e7-8b73-bfbcc35fd58c.png)

**Comment by evevkovacs** [comment] 2017-11-28 00:16
Focussing on "rest-frame no dust", you say the differences are ~few x .01 mags. Can this reasonably be accounted for by the differences between the SED template  fit by CatSim and the "true SED", which is only coarsely approximated by the SED filter luminosities supplied by Galacticus? The width of the wavelength bins for the SED filters in Galacticus varied from 250- 600 angstroms over the wavelength range 3000-10000 angstroms, so there's some slop there. For example, u-band effectively covers the range 3200 -4050, and is spanned by 3 Galacticus SED filters. And most of the filter  throughput  goes into just one SED filter.  I have no feel for how much SED templates vary in this wavelength range. How good are the SED fits?

**Comment by danielsf** [comment] 2017-11-28 00:47
I am attaching a text file that lists the magnitudes (unnormalized by any distance modulus) of the CatSim SEDs in each of the Galacticus tophat bands.  I'm not sure which plots would be most helpful, so I'm just going to put the data here.

I do suspect that what we are seeing is the natural slop one would expect from approximating one SED grid (Galacticus) with another (CatSim).  I don't have a strong opinion whether or not this much slop is acceptable or not.
[CatSimMagGrid.txt](https://github.com/LSSTDESC/DC2_Repo/files/1508128/CatSimMagGrid.txt)

**Comment by katrinheitmann** [comment] 2017-12-22 01:03
For now we agreed that due to the approximations the slop is expected. So I will close this issue. If people feel like we need more tests we should reopen.

**Closed by katrinheitmann** 2017-12-22 01:03 UTC
